// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sms.proto

package cn.bigcoder.demo.grpc.sms.proto;

public final class SmsProto {
  private SmsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SmsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:news.SmsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送短信的手机号
     * </pre>
     *
     * <code>repeated string phoneNumber = 1;</code>
     * @return A list containing the phoneNumber.
     */
    java.util.List<java.lang.String>
        getPhoneNumberList();
    /**
     * <pre>
     * 发送短信的手机号
     * </pre>
     *
     * <code>repeated string phoneNumber = 1;</code>
     * @return The count of phoneNumber.
     */
    int getPhoneNumberCount();
    /**
     * <pre>
     * 发送短信的手机号
     * </pre>
     *
     * <code>repeated string phoneNumber = 1;</code>
     * @param index The index of the element to return.
     * @return The phoneNumber at the given index.
     */
    java.lang.String getPhoneNumber(int index);
    /**
     * <pre>
     * 发送短信的手机号
     * </pre>
     *
     * <code>repeated string phoneNumber = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phoneNumber at the given index.
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes(int index);

    /**
     * <pre>
     * 短信内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 短信内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code news.SmsRequest}
   */
  public static final class SmsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:news.SmsRequest)
      SmsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SmsRequest.newBuilder() to construct.
    private SmsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SmsRequest() {
      phoneNumber_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SmsRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SmsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                phoneNumber_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              phoneNumber_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          phoneNumber_ = phoneNumber_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest.class, cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest.Builder.class);
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList phoneNumber_;
    /**
     * <pre>
     * 发送短信的手机号
     * </pre>
     *
     * <code>repeated string phoneNumber = 1;</code>
     * @return A list containing the phoneNumber.
     */
    public com.google.protobuf.ProtocolStringList
        getPhoneNumberList() {
      return phoneNumber_;
    }
    /**
     * <pre>
     * 发送短信的手机号
     * </pre>
     *
     * <code>repeated string phoneNumber = 1;</code>
     * @return The count of phoneNumber.
     */
    public int getPhoneNumberCount() {
      return phoneNumber_.size();
    }
    /**
     * <pre>
     * 发送短信的手机号
     * </pre>
     *
     * <code>repeated string phoneNumber = 1;</code>
     * @param index The index of the element to return.
     * @return The phoneNumber at the given index.
     */
    public java.lang.String getPhoneNumber(int index) {
      return phoneNumber_.get(index);
    }
    /**
     * <pre>
     * 发送短信的手机号
     * </pre>
     *
     * <code>repeated string phoneNumber = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phoneNumber at the given index.
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes(int index) {
      return phoneNumber_.getByteString(index);
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 短信内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 短信内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < phoneNumber_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, phoneNumber_.getRaw(i));
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < phoneNumber_.size(); i++) {
          dataSize += computeStringSizeNoTag(phoneNumber_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhoneNumberList().size();
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest)) {
        return super.equals(obj);
      }
      cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest other = (cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest) obj;

      if (!getPhoneNumberList()
          .equals(other.getPhoneNumberList())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPhoneNumberCount() > 0) {
        hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNumberList().hashCode();
      }
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code news.SmsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:news.SmsRequest)
        cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest.class, cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest.Builder.class);
      }

      // Construct using cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        phoneNumber_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsRequest_descriptor;
      }

      @java.lang.Override
      public cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest getDefaultInstanceForType() {
        return cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest build() {
        cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest buildPartial() {
        cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest result = new cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          phoneNumber_ = phoneNumber_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.phoneNumber_ = phoneNumber_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest) {
          return mergeFrom((cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest other) {
        if (other == cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest.getDefaultInstance()) return this;
        if (!other.phoneNumber_.isEmpty()) {
          if (phoneNumber_.isEmpty()) {
            phoneNumber_ = other.phoneNumber_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePhoneNumberIsMutable();
            phoneNumber_.addAll(other.phoneNumber_);
          }
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList phoneNumber_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhoneNumberIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          phoneNumber_ = new com.google.protobuf.LazyStringArrayList(phoneNumber_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 发送短信的手机号
       * </pre>
       *
       * <code>repeated string phoneNumber = 1;</code>
       * @return A list containing the phoneNumber.
       */
      public com.google.protobuf.ProtocolStringList
          getPhoneNumberList() {
        return phoneNumber_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 发送短信的手机号
       * </pre>
       *
       * <code>repeated string phoneNumber = 1;</code>
       * @return The count of phoneNumber.
       */
      public int getPhoneNumberCount() {
        return phoneNumber_.size();
      }
      /**
       * <pre>
       * 发送短信的手机号
       * </pre>
       *
       * <code>repeated string phoneNumber = 1;</code>
       * @param index The index of the element to return.
       * @return The phoneNumber at the given index.
       */
      public java.lang.String getPhoneNumber(int index) {
        return phoneNumber_.get(index);
      }
      /**
       * <pre>
       * 发送短信的手机号
       * </pre>
       *
       * <code>repeated string phoneNumber = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the phoneNumber at the given index.
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes(int index) {
        return phoneNumber_.getByteString(index);
      }
      /**
       * <pre>
       * 发送短信的手机号
       * </pre>
       *
       * <code>repeated string phoneNumber = 1;</code>
       * @param index The index to set the value at.
       * @param value The phoneNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneNumber(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumberIsMutable();
        phoneNumber_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送短信的手机号
       * </pre>
       *
       * <code>repeated string phoneNumber = 1;</code>
       * @param value The phoneNumber to add.
       * @return This builder for chaining.
       */
      public Builder addPhoneNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumberIsMutable();
        phoneNumber_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送短信的手机号
       * </pre>
       *
       * <code>repeated string phoneNumber = 1;</code>
       * @param values The phoneNumber to add.
       * @return This builder for chaining.
       */
      public Builder addAllPhoneNumber(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhoneNumberIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneNumber_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送短信的手机号
       * </pre>
       *
       * <code>repeated string phoneNumber = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoneNumber() {
        phoneNumber_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送短信的手机号
       * </pre>
       *
       * <code>repeated string phoneNumber = 1;</code>
       * @param value The bytes of the phoneNumber to add.
       * @return This builder for chaining.
       */
      public Builder addPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePhoneNumberIsMutable();
        phoneNumber_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 短信内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 短信内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 短信内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 短信内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 短信内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:news.SmsRequest)
    }

    // @@protoc_insertion_point(class_scope:news.SmsRequest)
    private static final cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest();
    }

    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SmsRequest>
        PARSER = new com.google.protobuf.AbstractParser<SmsRequest>() {
      @java.lang.Override
      public SmsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SmsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SmsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SmsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SmsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:news.SmsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    java.lang.String getResult();
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * Protobuf type {@code news.SmsResponse}
   */
  public static final class SmsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:news.SmsResponse)
      SmsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SmsResponse.newBuilder() to construct.
    private SmsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SmsResponse() {
      result_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SmsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SmsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              result_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse.class, cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object result_;
    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      }
    }
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse)) {
        return super.equals(obj);
      }
      cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse other = (cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse) obj;

      if (!getResult()
          .equals(other.getResult())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code news.SmsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:news.SmsResponse)
        cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse.class, cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse.Builder.class);
      }

      // Construct using cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.bigcoder.demo.grpc.sms.proto.SmsProto.internal_static_news_SmsResponse_descriptor;
      }

      @java.lang.Override
      public cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse getDefaultInstanceForType() {
        return cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse build() {
        cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse buildPartial() {
        cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse result = new cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse) {
          return mergeFrom((cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse other) {
        if (other == cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse.getDefaultInstance()) return this;
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>string result = 1;</code>
       * @return The result.
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       * @return The bytes for result.
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       * @param value The bytes for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        result_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:news.SmsResponse)
    }

    // @@protoc_insertion_point(class_scope:news.SmsResponse)
    private static final cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse();
    }

    public static cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SmsResponse>
        PARSER = new com.google.protobuf.AbstractParser<SmsResponse>() {
      @java.lang.Override
      public SmsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SmsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SmsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SmsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.bigcoder.demo.grpc.sms.proto.SmsProto.SmsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_SmsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_SmsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_SmsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_SmsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tsms.proto\022\004news\"2\n\nSmsRequest\022\023\n\013phone" +
      "Number\030\001 \003(\t\022\017\n\007content\030\002 \001(\t\"\035\n\013SmsResp" +
      "onse\022\016\n\006result\030\001 \001(\t2@\n\nSmsService\0222\n\007se" +
      "ndSms\022\020.news.SmsRequest\032\021.news.SmsRespon" +
      "se\"\0000\001B-\n\037cn.bigcoder.demo.grpc.sms.prot" +
      "oB\010SmsProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_news_SmsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_news_SmsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_SmsRequest_descriptor,
        new java.lang.String[] { "PhoneNumber", "Content", });
    internal_static_news_SmsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_news_SmsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_SmsResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
